// This file is auto-generated by @hey-api/openapi-ts

import type { GetApiPostsResponse, GetApiTagsByNameResponse, GetApiArchiveResponse } from './types.gen.ts';

const postDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const pagedDataOfPostDtoSchemaResponseTransformer = (data: any) => {
    data.records = data.records.map((item: any) => {
        return postDtoSchemaResponseTransformer(item);
    });
    return data;
};

export const getApiPostsResponseTransformer = async (data: any): Promise<GetApiPostsResponse> => {
    data = pagedDataOfPostDtoSchemaResponseTransformer(data);
    return data;
};

const postArchiveDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const getApiTagsByNameResponseTransformer = async (data: any): Promise<GetApiTagsByNameResponse> => {
    data = data.map((item: any) => {
        return postArchiveDtoSchemaResponseTransformer(item);
    });
    return data;
};

const archiveDtoSchemaResponseTransformer = (data: any) => {
    data.posts = data.posts.map((item: any) => {
        return postArchiveDtoSchemaResponseTransformer(item);
    });
    return data;
};

export const getApiArchiveResponseTransformer = async (data: any): Promise<GetApiArchiveResponse> => {
    data = data.map((item: any) => {
        return archiveDtoSchemaResponseTransformer(item);
    });
    return data;
};